[package]
name = "git-intelligence-message"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"]}
dirs = "5.0"
toml = "0.8"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"]}
tokio = { version = "1", features = ["full"] }
validator = { version = "0.16", features = ["derive"]}

[[bin]]
name = "gim"
path = "src/main.rs"
